version: "3.8"

services:
  miningcore:
    image: coinfoundry/miningcore-docker:latest
    container_name: etc-stratum
    restart: unless-stopped
    ports:
      - "3333:3333"
    volumes:
      - ./config.json:/config.json:ro
